### ISSUE TITLE
tyranny Negative search option

### ISSUE THREAD

**Issue by onedayakub** [pharaox/artifact_trade#3] opened 2023-07-31 16:43 UTC
at_modifier->"at_tyranny" search option only shows the "tyranny gain +10%" and "tyranny reduction" modifier. 
The option to search for negative modifiers seems to be missing.
(example. Jeweled Danda: -20% Tyranny Gain)

This mod is awesome. I salute you for all your hard work.

**Comment by pharaox** [comment] 2023-09-03 10:58
@onedayakub Thanks a lot for your issue and PR! The issue is fixed with [commit](https://github.com/pharaox/artifact_trade/commit/8fc1aaf4cb4592287e32191614e79c094563f414). The fix is released with version 0.7.0.

**Closed as completed by pharaox** 2023-09-03 10:58 UTC
